from collections.abc import Sequence

MatchResult = tuple[str, dict[str, str], list[str]]
RouteInfo = tuple[str, str, str, list[str]]

class MethodNotAllowed(Exception):
    """Raised by `Router.match_route` when `path` matches a registered
    route but not for the requested method. `args[0]` is the list of
    methods that are allowed for that path."""

class Router:
    """The compiled routing engine. Subclassable (`korvex.Router`, in
    `korvex/router.py`, adds `.group()` this way) — plain Python
    subclasses of this type are supported."""

    def __init__(self) -> None: ...
    def add_route(
        self, path: str, handler_name: str, method: str = "GET", middleware: Sequence[str] | None = None
    ) -> None: ...
    def get(self, path: str, handler_name: str, middleware: Sequence[str] | None = None) -> None: ...
    def post(self, path: str, handler_name: str, middleware: Sequence[str] | None = None) -> None: ...
    def put(self, path: str, handler_name: str, middleware: Sequence[str] | None = None) -> None: ...
    def patch(self, path: str, handler_name: str, middleware: Sequence[str] | None = None) -> None: ...
    def delete(self, path: str, handler_name: str, middleware: Sequence[str] | None = None) -> None: ...
    def head(self, path: str, handler_name: str, middleware: Sequence[str] | None = None) -> None: ...
    def options(self, path: str, handler_name: str, middleware: Sequence[str] | None = None) -> None: ...
    def match_route(self, path: str, method: str = "GET") -> MatchResult | None: ...
    def remove_route(self, path: str, method: str = "GET") -> bool: ...
    def routes(self) -> list[RouteInfo]: ...
    def __repr__(self) -> str: ...
